name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Pacman (Light Mode)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: MNR-Tushar
          template: classic
          base: ""
          config_timezone: Asia/Dhaka
          plugin_pagespeed: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          filename: pacman-contribution-graph.svg
          
      - name: Generate Pacman (Dark Mode)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: MNR-Tushar
          template: classic
          base: ""
          config_timezone: Asia/Dhaka
          config_twemoji: yes
          plugin_pagespeed: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          extras_css: |
            * { color: white !important; }
          filename: pacman-contribution-graph-dark.svg
          
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
